TOP=..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
DB += ca_drive.db
DB += CircBuff.db
DB += Count.db
DB += drive.db
DB += trig.db
DB += 100CalcBuff.db
DB += 10CalcBuff.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

